// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

namespace WHMS.Data.Migrations
{
    public partial class FixTableNames : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Orders_ShippingMethod_ShippingMethodId",
                table: "Orders");

            migrationBuilder.DropForeignKey(
                name: "FK_ProductWarehouse_Products_ProductId",
                table: "ProductWarehouse");

            migrationBuilder.DropForeignKey(
                name: "FK_ProductWarehouse_Warehouse_WarehouseId",
                table: "ProductWarehouse");

            migrationBuilder.DropForeignKey(
                name: "FK_ShippingMethod_Carrier_CarrierId",
                table: "ShippingMethod");

            migrationBuilder.DropForeignKey(
                name: "FK_Warehouse_Addresses_AddressId",
                table: "Warehouse");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Warehouse",
                table: "Warehouse");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ShippingMethod",
                table: "ShippingMethod");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ProductWarehouse",
                table: "ProductWarehouse");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Carrier",
                table: "Carrier");

            migrationBuilder.RenameTable(
                name: "Warehouse",
                newName: "Warehouses");

            migrationBuilder.RenameTable(
                name: "ShippingMethod",
                newName: "ShippingMethods");

            migrationBuilder.RenameTable(
                name: "ProductWarehouse",
                newName: "ProductWarehouses");

            migrationBuilder.RenameTable(
                name: "Carrier",
                newName: "Carriers");

            migrationBuilder.RenameIndex(
                name: "IX_Warehouse_IsDeleted",
                table: "Warehouses",
                newName: "IX_Warehouses_IsDeleted");

            migrationBuilder.RenameIndex(
                name: "IX_Warehouse_AddressId",
                table: "Warehouses",
                newName: "IX_Warehouses_AddressId");

            migrationBuilder.RenameIndex(
                name: "IX_ShippingMethod_IsDeleted",
                table: "ShippingMethods",
                newName: "IX_ShippingMethods_IsDeleted");

            migrationBuilder.RenameIndex(
                name: "IX_ShippingMethod_CarrierId",
                table: "ShippingMethods",
                newName: "IX_ShippingMethods_CarrierId");

            migrationBuilder.RenameIndex(
                name: "IX_ProductWarehouse_ProductId",
                table: "ProductWarehouses",
                newName: "IX_ProductWarehouses_ProductId");

            migrationBuilder.RenameIndex(
                name: "IX_Carrier_IsDeleted",
                table: "Carriers",
                newName: "IX_Carriers_IsDeleted");

            migrationBuilder.AddColumn<int>(
                name: "WarehouseId",
                table: "Orders",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "ShippingMethods",
                maxLength: 50,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Carriers",
                maxLength: 20,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Warehouses",
                table: "Warehouses",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ShippingMethods",
                table: "ShippingMethods",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ProductWarehouses",
                table: "ProductWarehouses",
                columns: new[] { "WarehouseId", "ProductId" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Carriers",
                table: "Carriers",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_WarehouseId",
                table: "Orders",
                column: "WarehouseId");

            migrationBuilder.AddForeignKey(
                name: "FK_Orders_ShippingMethods_ShippingMethodId",
                table: "Orders",
                column: "ShippingMethodId",
                principalTable: "ShippingMethods",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Orders_Warehouses_WarehouseId",
                table: "Orders",
                column: "WarehouseId",
                principalTable: "Warehouses",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProductWarehouses_Products_ProductId",
                table: "ProductWarehouses",
                column: "ProductId",
                principalTable: "Products",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProductWarehouses_Warehouses_WarehouseId",
                table: "ProductWarehouses",
                column: "WarehouseId",
                principalTable: "Warehouses",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ShippingMethods_Carriers_CarrierId",
                table: "ShippingMethods",
                column: "CarrierId",
                principalTable: "Carriers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Warehouses_Addresses_AddressId",
                table: "Warehouses",
                column: "AddressId",
                principalTable: "Addresses",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Orders_ShippingMethods_ShippingMethodId",
                table: "Orders");

            migrationBuilder.DropForeignKey(
                name: "FK_Orders_Warehouses_WarehouseId",
                table: "Orders");

            migrationBuilder.DropForeignKey(
                name: "FK_ProductWarehouses_Products_ProductId",
                table: "ProductWarehouses");

            migrationBuilder.DropForeignKey(
                name: "FK_ProductWarehouses_Warehouses_WarehouseId",
                table: "ProductWarehouses");

            migrationBuilder.DropForeignKey(
                name: "FK_ShippingMethods_Carriers_CarrierId",
                table: "ShippingMethods");

            migrationBuilder.DropForeignKey(
                name: "FK_Warehouses_Addresses_AddressId",
                table: "Warehouses");

            migrationBuilder.DropIndex(
                name: "IX_Orders_WarehouseId",
                table: "Orders");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Warehouses",
                table: "Warehouses");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ShippingMethods",
                table: "ShippingMethods");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ProductWarehouses",
                table: "ProductWarehouses");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Carriers",
                table: "Carriers");

            migrationBuilder.DropColumn(
                name: "WarehouseId",
                table: "Orders");

            migrationBuilder.RenameTable(
                name: "Warehouses",
                newName: "Warehouse");

            migrationBuilder.RenameTable(
                name: "ShippingMethods",
                newName: "ShippingMethod");

            migrationBuilder.RenameTable(
                name: "ProductWarehouses",
                newName: "ProductWarehouse");

            migrationBuilder.RenameTable(
                name: "Carriers",
                newName: "Carrier");

            migrationBuilder.RenameIndex(
                name: "IX_Warehouses_IsDeleted",
                table: "Warehouse",
                newName: "IX_Warehouse_IsDeleted");

            migrationBuilder.RenameIndex(
                name: "IX_Warehouses_AddressId",
                table: "Warehouse",
                newName: "IX_Warehouse_AddressId");

            migrationBuilder.RenameIndex(
                name: "IX_ShippingMethods_IsDeleted",
                table: "ShippingMethod",
                newName: "IX_ShippingMethod_IsDeleted");

            migrationBuilder.RenameIndex(
                name: "IX_ShippingMethods_CarrierId",
                table: "ShippingMethod",
                newName: "IX_ShippingMethod_CarrierId");

            migrationBuilder.RenameIndex(
                name: "IX_ProductWarehouses_ProductId",
                table: "ProductWarehouse",
                newName: "IX_ProductWarehouse_ProductId");

            migrationBuilder.RenameIndex(
                name: "IX_Carriers_IsDeleted",
                table: "Carrier",
                newName: "IX_Carrier_IsDeleted");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "ShippingMethod",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldMaxLength: 50,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Carrier",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldMaxLength: 20,
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Warehouse",
                table: "Warehouse",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ShippingMethod",
                table: "ShippingMethod",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ProductWarehouse",
                table: "ProductWarehouse",
                columns: new[] { "WarehouseId", "ProductId" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Carrier",
                table: "Carrier",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Orders_ShippingMethod_ShippingMethodId",
                table: "Orders",
                column: "ShippingMethodId",
                principalTable: "ShippingMethod",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProductWarehouse_Products_ProductId",
                table: "ProductWarehouse",
                column: "ProductId",
                principalTable: "Products",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProductWarehouse_Warehouse_WarehouseId",
                table: "ProductWarehouse",
                column: "WarehouseId",
                principalTable: "Warehouse",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ShippingMethod_Carrier_CarrierId",
                table: "ShippingMethod",
                column: "CarrierId",
                principalTable: "Carrier",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Warehouse_Addresses_AddressId",
                table: "Warehouse",
                column: "AddressId",
                principalTable: "Addresses",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
